version: '2'
services:
    db:
        platform: linux/x86_64
        image: mysql:5.6
        volumes:
            - "./docker/.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: iot
            MYSQL_DATABASE: iot
        ports:
            - "3307:3306"
    php:
        build: ./docker
        volumes:
          - ".:/var/www/html"
        ports:
            - 8182:80
        restart: always
#    mqtt:
#        image: eclipse-mosquitto
#        container_name: mqtt-broker
#        ports:
#            - 1883:1883
#            - 9001:9001
#        volumes:
#            - "./docker/mosquitto/config:/mosquitto/config"
#            - "./docker/mosquitto/data:/mosquitto/data"
#            - "./docker/mosquitto/log:/mosquitto/log"
#    mqtt-explorer:
#        image: smeagolworms4/mqtt-explorer
#        ports:
#            - 4000:4000
#        volumes:
#            - ./configs/mqtt-explorer:/mqtt-explorer/config

